# Generated by Django 5.1.6 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('completed_lessons', models.JSONField(blank=True, default=list)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.CreateModel(
            name='SkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('leetcode', 'LeetCode'), ('codeforces', 'Codeforces'), ('github', 'GitHub'), ('manual', 'Manual')], max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('topic_scores', models.JSONField(blank=True, default=dict)),
                ('weekly_activity', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
