# Generated by Django 5.1.6 on 2026-03-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'course')},
        ),
    ]
