# Generated by Django 5.1.6 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('estimated_duration_weeks', models.PositiveIntegerField(default=2)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('target_skills', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('difficulty', 'title'),
            },
        ),
    ]
