# Generated by Django 5.1.6 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('experience_level', models.CharField(max_length=20)),
                ('recommended_technologies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoadmapMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('week_start', models.PositiveIntegerField()),
                ('week_end', models.PositiveIntegerField()),
                ('resources', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('order', 'week_start'),
            },
        ),
    ]
